version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  integration-tester:
    container_name: integration-tester
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.tests.it
    volumes:
      - temp:/code
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:example@mysql:3306/pinkyring

  mysql-adminer:
    container_name: mysql-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql:
  temp:
