version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  mysql-adminer:
    container_name: mysql-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  rabbitmq:
    image: rabbitmq:3.11.2-management-alpine
    hostname: 'persistmydata' #https://stackoverflow.com/questions/41330514/docker-rabbitmq-persistency
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  
  apps-api-graphql:
    container_name: apps-api-graphql
    build:
      context: ./docker
      dockerfile: Dockerfile.app
    ports:
      - 4000:4000
    working_dir: /code/packages/apps/api-graphql
    volumes:
      - ./:/code
  
  apps-api-rest:
    container_name: apps-api-rest
    build:
      context: ./docker
      dockerfile: Dockerfile.app
    ports:
      - 3000:3000
    working_dir: /code/packages/apps/api-rest
    volumes:
      - ./:/code
  
  apps-chron-jobs:
    container_name: apps-chron-jobs
    build:
      context: ./docker
      dockerfile: Dockerfile.app
    working_dir: /code/packages/apps/chron-jobs
    volumes:
      - ./:/code

volumes:
  mysql:
  rabbitmq:

# api:
#   container_name: api-container
#   build:
#     context: ./docker
#     dockerfile: Dockerfile.api
#   ports:
#     - 3000:3000
#   working_dir: /code/packages/apps/api
#   volumes:
#     - ./:/code

# wait-for-example:
#   container_name: wait-for-example
#   image: alpine:3.16.2
#   command: sh -c './wait-for.sh www.eficode.com:80 -- echo "Eficode site is up"'
#   working_dir: /code
#   volumes:
#     - ./:/code
