service: pinkyring

provider:
  name: aws
  region: us-east-1
  stage: dev
  stackName: ${self:provider.stage}-${self:service.name}

custom:
  DB_USERNAME: root
  DB_PASSWORD: example
  DB_DATABASE_NAME: pinkyring
  DB_AUTOPAUSE: true
  DB_CAPACITY_MIN: 1
  DB_CAPACITY_MAX: 4
  DBClusterARN:
    Fn::Join:
      - ':'
      - - 'arn:aws:rds'
        - Ref: 'AWS::Region'
        - Ref: 'AWS::AccountId'
        - 'cluster'
        - !Ref AuroraDBCluster

functions:
  test-test:
    handler: ./packages/infrastructure/lambdas/build/test/test.handler
    events:
      - httpApi:
          path: /
          method: GET

  test-getData:
    handler: ./packages/infrastructure/lambdas/build/test/getData.handler
    events:
      - httpApi:
          path: /getData
          method: GET
  
  todo-getTodos:
    handler: ./packages/infrastructure/lambdas/build/todo/getTodos.handler
    events:
      - httpApi:
          path: /todo/getTodos
          method: GET
  
  todo-createTodo:
    handler: ./packages/infrastructure/lambdas/build/todo/createTodo.handler
    events:
      - httpApi:
          path: /todo/createTodo
          method: GET

resources:
  - ${file(serverless/resources/vpc.yml)}
  - ${file(serverless/resources/rds.yml)}
  - ${file(serverless/resources/custom/dbmigration.yml)}
