service: pinkyring

provider:
  name: aws
  region: us-east-1
  stage: test
  stackName: ${self:provider.stage}-${self:service}
  timeout: 29
  vpc:
    securityGroupIds:
      - !Ref PublicSecurityGroup
    subnetIds:
      - !Ref SubnetAPublic
      - !Ref SubnetBPublic
  environment:
    NODE_ENV: ${self:provider.stage}
    DATABASE_URL:
      Fn::Join:
        - ''
        - - 'mysql://'
          - ${self:custom.DB_USERNAME}
          - ':'
          - ${self:custom.DB_PASSWORD}
          - '@'
          - Fn::GetAtt: [AuroraDBCluster, Endpoint.Address]
          - ':3306/'
          - ${self:custom.DB_DATABASE_NAME}
          - '?connection_limit=1'
          - '&pool_timeout=30'
    BlogPostAddedTopicArn:
      Fn::GetAtt: [BlogPostAddedTopic, Arn]
  ecr:
    images:
      db-migration-runner:
        # this relies on the prisma folder existing in the same directory
        # the github deploy action includes a step that handles copying the prisma folder
        path: ./serverless/dbmigration/

custom:
  DB_USERNAME: root
  DB_PASSWORD: example!
  DB_DATABASE_NAME: pinkyring
  DB_AUTOPAUSE: true
  DB_CAPACITY_MIN: 1
  DB_CAPACITY_MAX: 1
  DBClusterARN:
    Fn::Join:
      - ':'
      - - 'arn:aws:rds'
        - Ref: 'AWS::Region'
        - Ref: 'AWS::AccountId'
        - 'cluster'
        - !Ref AuroraDBCluster

functions:
  test-test:
    handler: ./packages/infrastructure/aws/lambdas/build/test/test.handler
    events:
      - httpApi:
          path: /
          method: GET

  test-getData:
    handler: ./packages/infrastructure/aws/lambdas/build/test/getData.handler
    events:
      - httpApi:
          path: /getData
          method: GET
  
  todo-getTodos:
    handler: ./packages/infrastructure/aws/lambdas/build/todo/getTodos.handler
    events:
      - httpApi:
          path: /todo/getTodos
          method: GET
  
  todo-createTodo:
    handler: ./packages/infrastructure/aws/lambdas/build/todo/createTodo.handler
    events:
      - httpApi:
          path: /todo/createTodo
          method: POST
  
  graphql:
    handler: ./packages/infrastructure/aws/lambdas/build/graphql/server.graphqlHandler
    events:
      - httpApi:
          path: /graphql
          method: GET
      - httpApi:
          path: /graphql
          method: POST
  
  DBMigration:
    image:
      name: db-migration-runner
    # role: DBMigrationRole
  
  blogPostAddedEvent:
    handler: ./packages/infrastructure/aws/lambdas/build/events/blogPostAdded.handler
    events:
      - sqs: 
          arn: 
            Fn::GetAtt: [BlogPostAddedQueue, Arn]
  
  createBlogPostEvent:
    handler: ./packages/infrastructure/aws/lambdas/build/events/createBlogPostEvent.handler
    events:
      - httpApi:
          path: /events/createBlogPostEvent
          method: GET

resources:
  - ${file(serverless/resources/vpc.yml)}
  - ${file(serverless/resources/rds.yml)}
  - ${file(serverless/resources/queue.yml)}
  #- ${file(serverless/resources/custom/dbmigration.yml)}

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - '!.github'
    - '!docker'
    - '!serverless'
    - '!packages/**'
    - 'packages/**/build/**/*.js'
    - '!package-lock.json'
