service: aws-node

provider:
  name: aws

functions:
  test:
    handler: ./packages/infrastructure/lambdas/build/test/test.handler
    events:
      - httpApi:
          path: /
          method: GET
