service: aws-node

provider:
  name: aws

functions:
  test-test:
    handler: ./packages/infrastructure/lambdas/build/test/test.handler
    events:
      - httpApi:
          path: /
          method: GET
  test-getData:
    handler: ./packages/infrastructure/lambdas/build/test/getData.handler
    events:
      - httpApi:
          path: /getData
          method: GET
