# prisma needs open ssl 1.1.x and some docker images are moving to open ssl 3
# https://github.com/prisma/prisma/issues/16553#issuecomment-1353302617
# https://github.com/prisma/prisma/issues/14073#issuecomment-1351560775
FROM node:18.12.1-alpine3.16

# have to run prisma generate in the environment where prisma will run
# so it can use the correct environment files (windows, linux, or whatever)
# the app containers are going to rely on this

# then wait for mysql to start
# and then deploy the schema and seed the database

CMD npm run prisma generate && ./docker/wait-for.sh mysql:3306 -- npm run prisma migrate deploy && npm run prisma db seed
