Resources:
  DBMigrationCustomResource:
    Type: 'Custom::DBMigration'
    Version: '0.1'
    DependsOn:
    - DBMigrationLambdaFunction
    Properties:
      ServiceToken:
        Fn::GetAtt: [ DBMigrationLambdaFunction, Arn ]
      Version: 001
  
  DBMigrationRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole #communicate with resources within a vpc
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - rds-data:ExecuteStatement
            - rds-data:BeginTransaction
            - rds-data:RollbackTransaction
            - rds-data:CommitTransaction
            Effect: Allow
            Resource:
              - ${self:custom.DBClusterARN}
          Version: '2012-10-17'
        PolicyName: ${self:provider.stackName}-DBMigration-GeneratedRoles
      RoleName: ${self:provider.stackName}-DBMigration
