Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: ${self:provider.stackName}-DBSubnetGroup
      SubnetIds:
        - !Ref SubnetAPrivate
        - !Ref SubnetBPrivate

  DBClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref 'AWS::StackName'
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: ${self:provider.stackName}-AuroraClusterSecurityGroup
  
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: ${self:custom.DB_USERNAME}
      MasterUserPassword: ${self:custom.DB_PASSWORD}
      DatabaseName: ${self:custom.DB_DATABASE_NAME}
      Engine: aurora-mysql
      EngineMode: serverless
      EngineVersion: "2.07.1"
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
      - !Ref DBClusterSecurityGroup  
      ScalingConfiguration:
        AutoPause: ${self:custom.DB_AUTOPAUSE}
        MinCapacity: ${self:custom.DB_CAPACITY_MIN}
        MaxCapacity: ${self:custom.DB_CAPACITY_MAX}
