export enum BASE_DATA_ACTIONS {
  CREATE = 'BASE_DATA_ACTIONS.CREATE',
  UPDATE = 'BASE_DATA_ACTIONS.UPDATE',
  DELETE = 'BASE_DATA_ACTIONS.DELETE',
}

export enum SPECIFIC_ACTIONS {
  SPECIAL_UPDATE = 'SPECIFIC_ACTIONS.SPECIAL_UPDATE',
}

export type DATA_ACTION = BASE_DATA_ACTIONS | SPECIFIC_ACTIONS;
